# Generated by Django 2.2 on 2019-07-05 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyReference', models.CharField(max_length=20)),
                ('oic', models.CharField(max_length=20)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('exhibitRef', models.CharField(max_length=30)),
                ('seizedDate', models.DateField()),
                ('seizedTime', models.TimeField()),
                ('description', models.CharField(max_length=40)),
                ('seizedLocation', models.CharField(max_length=60)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='manxflag.jpg', null=True, upload_to='home/tolca/property/media/', verbose_name='add image')),
                ('thumbnail', models.ImageField(null=True, upload_to='product-thumbnails')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
    ]
