# Generated by Django 2.2 on 2019-07-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190706_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='home/tolca/property/media/'),
        ),
    ]
