# Generated by Django 2.2 on 2019-07-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190706_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='propertyReference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
