# Generated by Django 2.2 on 2019-07-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190712_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(default='manxflag.jpg', null=True, upload_to='home/tolca/property/media/', verbose_name='add image'),
        ),
    ]
