# Generated by Django 2.2 on 2019-07-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190717_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(null=True, upload_to='home/tolca/property/media/', verbose_name='add image'),
        ),
    ]
